version: "3.7"
services:
  web:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    command: 'ruby app.rb'
    volumes:
      - ".:/campaign_sync"
      - bundle:/bundle
    ports:
      - "3000:3000"
volumes:
  bundle:
